[package]
name = "lottery"
version = "0.0.1"

[dependencies.SupraVrf]
git = "https://github.com/Entropy-Foundation/vrf-interface"
subdir = "supra/testnet"
rev = "master"

[addresses]
MoveStdlib = "0x1"
AptosStdlib = "0x1"
SupraFramework = "0x1"
SupraVrf = "0x1"
lottery = "0x3bd5cb43528ea967459e0741d8120fa4472f0c580a8b7c04f598cc3dd3341fbc"
vrf_validator = "0x186ba2ba88f4a14ca51f6ce42702c7ebdf6bfcf738d897cc98b986ded6f1219e"