[package]
name = "lottery"
version = "0.0.1"

[dependencies]
MoveStdlib = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/move-stdlib", rev = "dev" }
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/supra-framework", rev = "dev" }
vrf_hub = { local = "../../SupraLottery/supra/move_workspace/vrf_hub" }
lottery_factory = { local = "../../SupraLottery/supra/move_workspace/lottery_factory" }
SupraVrf = { local = "../../SupraLottery/supra/move_workspace/SupraVrf" }

[addresses]
std = "0x1"
MoveStdlib = "0x1"
SupraFramework = "0x1"
supra_addr = "0x186ba2ba88f4a14ca51f6ce42702c7ebdf6bfcf738d897cc98b986ded6f1219e"
lottery = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"
vrf_hub = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"
lottery_factory = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"

[dev-addresses]
lottery_owner = "0x103"
lottery_contract = "0x104"
player1 = "0x105"
player2 = "0x106"
player3 = "0x107"
player4 = "0x108"
jackpot_pool = "0x109"
operations_pool = "0x10a"
