[package]
name = "lottery"
version = "0.0.1"

[dependencies.SupraVrf]
git = "https://github.com/Entropy-Foundation/vrf-interface"
subdir = "supra/testnet"
rev = "master"

[addresses]
MoveStdlib = "0x1"
AptosStdlib = "0x1"
SupraFramework = "0x1"
SupraVrf = "0x1"
lottery = "0x50989d6bf578d211a2f3b54833e3a1e3c5864ec64f9b24bad6d24a7bd69e9cde"
vrf_validator = "0x186ba2ba88f4a14ca51f6ce42702c7ebdf6bfcf738d897cc98b986ded6f1219e"
