[package]
name = "lottery_factory"
version = "0.0.1"

[addresses]
std = "0x1"
lottery_factory = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"
vrf_hub = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"

[dependencies]
MoveStdlib = { local = "../move-stdlib" }
vrf_hub = { local = "../vrf_hub" }
SupraFramework = { git = "https://github.com/Entropy-Foundation/aptos-core.git", subdir = "aptos-move/framework/supra-framework", rev = "dev" }
