[package]
name = "lottery_factory"
version = "0.0.1"

[addresses]
std = "0x1"
lottery_factory = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"
lottery_vrf_gateway = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"

[dependencies]
MoveStdlib = { workspace = true }
lottery_vrf_gateway = { local = "../lottery_vrf_gateway" }
SupraFramework = { workspace = true }

