[package]
name = "lottery_utils"
version = "0.1.0"

[addresses]
std = "0x1"
MoveStdlib = "0x1"
SupraFramework = "0x1"
lottery = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"
lottery_utils = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"
lottery_vrf_gateway = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"

[dependencies]
MoveStdlib = { workspace = true }
SupraFramework = { workspace = true }
lottery_data = { local = "../lottery_data" }
lottery_vrf_gateway = { local = "../lottery_vrf_gateway" }
