[workspace]
resolver = "v2"
members = [
  "lottery",
  "vrf_hub",
  "lottery_factory",
  "SupraVrf",
]

[package]
name = "supra_workspace"
version = "0.0.1"

[addresses]
lottery = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"
vrf_hub = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"
lottery_factory = "0x9a969d3b77941cec267f03b9bbb323c0333fa63d0e9e15204edabc415f134490"
supra_addr = "0x186ba2ba88f4a14ca51f6ce42702c7ebdf6bfcf738d897cc98b986ded6f1219e"
