[workspace]
resolver = "v2"
members = [
  "lottery_core",
  "lottery_support",
  "lottery_rewards",
  "vrf_hub",
  "lottery_factory",
  "SupraVrf",
  "lottery_multi"
]

[package]
name = "supra_workspace"
version = "0.0.1"

[addresses]
lottery = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"
vrf_hub = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"
lottery_factory = "0xbc959517601034979f21fa2f2f41862219ea38554be27c2fdb4fd9a392caafe0"
supra_addr = "0x186ba2ba88f4a14ca51f6ce42702c7ebdf6bfcf738d897cc98b986ded6f1219e"
lottery_multi_tests = "0xf00dbabe"
