[package]
name = 'SupraVrf'
version = '1.0.0'

[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = 'dev'

[addresses]
supra_addr = "{{supra_addr}}"
