[package]
name = 'SupraVrf'
version = '1.0.0'

[dependencies.SupraFramework]
git = 'https://github.com/Entropy-Foundation/aptos-core.git'
subdir = 'aptos-move/framework/supra-framework'
rev = '7d1e62c9a5394a279a73515a150e880200640f06'

[addresses]
supra_addr = "0x186ba2ba88f4a14ca51f6ce42702c7ebdf6bfcf738d897cc98b986ded6f1219e"
