name: Supra Move Tests

on:
  push:
    branches:
      - Test
      - master
  pull_request:
    branches:
      - Test
      - master

jobs:
  move-tests:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Pull Supra CLI image
        run: docker pull asia-docker.pkg.dev/supra-devnet-misc/supra-testnet/validator-node:v9.0.12

      - name: Run Supra Move tests
        env:
          SUPRA_HOME: /supra/configs
        run: |
          docker run --rm \
            -e SUPRA_HOME=/supra/configs \
            -v "${{ github.workspace }}/supra/configs:/supra/configs" \
            -v "${{ github.workspace }}/supra/move_workspace:/supra/move_workspace" \
            --entrypoint /supra/supra \
            asia-docker.pkg.dev/supra-devnet-misc/supra-testnet/validator-node:v9.0.12 \
            move test -p /supra/move_workspace
